version: '1-0'
services:
  web_dev:
    ports:
      - "80"  # Remove the port mapping to the host
    volumes:
      - /mnt/apache/dev/:/usr/local/apache2/htdocs/
    build: ./dev/
    limit:
        cpus: 0.1
        memory: 50M

  web_prod:
    ports:
      - "8081"  # Remove the port mapping to the host
    volumes:
      - /mnt/apache/prod/:/usr/local/apache2/htdocs/
    build: ./prod/
    limit:
        cpus: 0.1
        memory: 50M

  load_balancer:
    build:
      context: ./nginx/
      # build: ./nginx/
      limit:
        cpus: 0.1
        memory: 50M
    ports:
      - "80:80"  # Map port 80 of the load balancer container to port 80 of the host
