version: '1-0'
services:
  web_dev:
    container_name: web_dev
    mem_limit: 1g
    ports:
      - "80:80"
    volumes:
      - /mnt/apache/dev/:/usr/local/apache2/htdocs/
    build: ./dev/
  
  web_prod:
    container_name: web_prod
    mem_limit: 1g
    ports:
      - "8081:80"
    volumes:
      - /mnt/apache/prod/:/usr/local/apache2/htdocs/
    build: ./prod/
