version: '1-0'
services:
  web_dev:
    ports:
      - "80" 
    volumes:
      - /mnt/apache/dev/:/usr/local/apache2/htdocs/
    build: ./dev/
    mem_limit: 1g

  web_prod:
    ports:
      - "8081"  
    volumes:
      - /mnt/apache/prod/:/usr/local/apache2/htdocs/
    build: ./prod/
    mem_limit: 1g

  load_balancer:
    build:
      context: ./nginx/
      
    mem_limit: 1g
    ports:
      - "80:80"  
