FROM httpd:latest
EXPOSE 80
# RUN apt-get update && apt-get install -y \
#     vim \
#     git \
#     curl \
#     wget \
#     zip \
#     unzip \
#     && rm -rf /var/lib/apt/lists/*

# COPY /mnt/apache/dev /usr/local/apache2/htdocs/



